services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: books_management_system
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - wkallil-network
    volumes:
      - mysql_data:/var/lib/mysql

  books-management-system:
    image: wkallil/books-management-system
    restart: always
    working_dir: /books-management-system
    environment:
      TZ: America/Sao_Paulo
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/books_management_system?useTimezone=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${DB_MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_URL: jdbc:mysql://db:3306/books_management_system?useTimezone=true&serverTimezone=UTC
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: ${DB_MYSQL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      TEST_USERNAME: ${TEST_USERNAME}
      TEST_PASSWORD: ${TEST_PASSWORD}
    ports:
      - 8500:8500
    depends_on:
      - db
    networks:
      - wkallil-network

  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - wkallil-network

networks:
  wkallil-network:
    driver: bridge

volumes:
  mysql_data:
  portainer_data:
